model:
  _component_: torchtune.models.llama3_1.llama3_1_8b
  transformer_class:
    _component_cls_: torchtune.modules.transformer.HFTransformerDecoder

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /tmp/Meta-Llama-3.1-8B/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /tmp/Meta-Llama-3.1-8B/
  model_type: LLAMA3
